### ISSUE TITLE
`make check` python-errors in r3b with `ValueError: operands could not be broadcast together with shapes (31,) (0,)`.

### ISSUE THREAD

**Issue by dreirund** [auto-07p/auto-07p#37]
After having built auto-07p with  
```
./configure \
  --enable-plaut \
  --enable-plaut04 --enable-plaut04-qt \
  --with-openmp \
  --with-mpi \
  --enable-gui \
  --with-x \
  --with-optimization-flags="-Og -g3 -ggdb3" \
  --prefix="/opt/auto/07p" \
  FC="gfortan" \
  MPIFC="mpifort" \
  FFLAGS="-ggdb3" \
  CFLAGS="-Og -ggdb3 -g3 -Og -fno-lto -gdwarf-5 -ggdb3 -gno-strict-dwarf -g3 -gpubnames -grecord-gcc-switches -fno-eliminate-unused-debug-symbols -fvar-tracking -fvar-tracking-assignments -fdebug-types-section -fno-stack-protector -fno-omit-frame-pointer -D_FORTIFY_SOURCE=0 -DDEBUG" \
  CXXFLAGS="-Og -ggdb3 -g3 -Og -fno-lto -gdwarf-5 -ggdb3 -gno-strict-dwarf -g3 -gpubnames -grecord-gcc-switches -fno-eliminate-unused-debug-symbols -fvar-tracking -fvar-tracking-assignments -fdebug-types-section -fno-stack-protector -fno-omit-frame-pointer -D_FORTIFY_SOURCE=0 -DDEBUG"

make
```

a call of  
`make check`  
spills out the error  
```
[...]
***Compute libration points
mpifort -Ofast -fopenmp -O3 -c r3b.f90 -o r3b.o
mpifort -Ofast -fopenmp -O3 r3b.o -o r3b.exe /tmp/makepkg/build/auto-07p-git/src/auto/07p/lib/*.o
Starting r3b ...

  BR    PT  TY  LAB       mu         L2-NORM          x             y             z            ev1           ev2           ev3      
   1     1  EP    1   0.00000E+00   1.00000E+00   1.41070E-01   9.90000E-01   0.00000E+00   6.28319E+00   6.28319E+00   3.43182E+03
   1    25  BP    2  -5.87409E-11   1.00000E+00   4.99917E-01   8.66073E-01   0.00000E+00   6.28319E+00   6.28319E+00   0.00000E+00
   1    83  BP    3  -8.10663E-09   1.00000E+00   5.00000E-01  -8.66025E-01   0.00000E+00   6.28319E+00   6.28319E+00   0.00000E+00
   1   141  BP    4  -4.41108E-08   1.00000E+00  -1.00000E+00  -7.76934E-08   0.00000E+00   6.28319E+00   6.28319E+00   1.84647E+04
   1   181  UZ    5  -6.90239E-17   1.00000E+00  -1.33862E-01   9.91000E-01   0.00000E+00   6.28319E+00   6.28319E+00   0.00000E+00

  BR    PT  TY  LAB       mu         L2-NORM          x             y             z            ev1           ev2           ev3      
   2    13  UZ    6   6.30000E-02   9.70036E-01   4.37000E-01   8.66025E-01   0.00000E+00   6.28319E+00   0.00000E+00   0.00000E+00
   2    27  BP    7   1.00000E+00   1.00000E+00  -5.00000E-01   8.66025E-01   0.00000E+00   6.28319E+00   0.00000E+00   0.00000E+00
   2    29  UZ    8   1.10000E+00   1.05357E+00  -6.00000E-01   8.66025E-01   0.00000E+00   6.28319E+00   0.00000E+00   0.00000E+00

  BR    PT  TY  LAB       mu         L2-NORM          x             y             z            ev1           ev2           ev3      
   3    13  UZ    9   6.30000E-02   9.70036E-01   4.37000E-01  -8.66025E-01   0.00000E+00   6.28319E+00   0.00000E+00   0.00000E+00
   3    27  BP   10   1.00000E+00   1.00000E+00  -5.00000E-01  -8.66025E-01   0.00000E+00   6.28319E+00   0.00000E+00   0.00000E+00
   3    29  UZ   11   1.10000E+00   1.05357E+00  -6.00000E-01  -8.66025E-01   0.00000E+00   6.28319E+00   0.00000E+00   0.00000E+00

  BR    PT  TY  LAB       mu         L2-NORM          x             y             z            ev1           ev2           ev3      
   4    12  UZ   12   6.29987E-02   1.02624E+00  -1.02624E+00   4.30521E-55   0.00000E+00   5.98154E+00   6.11212E+00   0.00000E+00
   4    66  UZ   13   6.30047E-02   6.84812E-01   6.84812E-01   0.00000E+00   0.00000E+00   2.46895E+00   2.52972E+00   0.00000E+00
   4    76  UZ   14   6.30044E-02   1.23970E+00   1.23970E+00   0.00000E+00   0.00000E+00   3.65074E+00   3.82721E+00   0.00000E+00
   4    93  BP   15   1.00000E+00   9.99999E-01   9.99999E-01   0.00000E+00   0.00000E+00   6.28319E+00   6.28320E+00   2.75051E+03
   4    95  UZ   16   1.10000E+00   9.58386E-01   9.58386E-01   0.00000E+00   0.00000E+00   6.56369E+00   7.11528E+00   1.13984E+01

 Total Time    0.634E-01
r3b ... done
L1:
Traceback (most recent call last):
  File "r3b.auto", line 12, in <module>
    compute_lps.write_lagrange(r1)
  File "/tmp/makepkg/build/auto-07p-git/src/auto/07p/test/tmp/compute_lps.py", line 17, in write_lagrange
    period = x.PAR(parnumber)
             ^^^^^
  File "/tmp/makepkg/build/auto-07p-git/src/auto/07p/python/auto/parseS.py", line 1018, in __getattr__
    self.__readAll()
  File "/tmp/makepkg/build/auto-07p-git/src/auto/07p/python/auto/parseS.py", line 941, in __readAll
    fdata = self.__input.readfloats(self.__index, total)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/makepkg/build/auto-07p-git/src/auto/07p/python/auto/parseS.py", line 159, in readfloats
    if fdata == [] or len(fdata) != total:
       ^^^^^^^^^^^
ValueError: operands could not be broadcast together with shapes (31,) (0,) 
[...]
Major errors found in: fnb fnc r3b snh
Please point your web browser to the following URL for detailed results:
file:/tmp/makepkg/build/auto-07p-git/src/auto/07p/test/verification/index.html
make: *** [Makefile:116: check] Error 1
```

As it can be seen, issues were also in fnb, fnc and snh, which I have not spotted by sporadically watching the terminal.

I attach the test result folder `test/verification` as an archive: [`verification.tar.gz`](https://github.com/auto-07p/auto-07p/files/12522978/verification.tar.gz).

Python version: 3.11.3.

Regards!

**Comment by znicolaou** [comment]
Hello @dreirund -- I believe encountered this issue also and found that it is related to a change in numpy's elementwise comparison with the empty list. Try downgrading numpy (I'm using 1.23.5, with conda as in `conda install numpy=1.23.5`), or changing line 159 of ParseS.py from
```
            if fdata == [] or len(fdata) != total:
```
to 
```
            if fdata.tolist() == [] or len(fdata) != total:
```

**Comment by dreirund** [comment]
Ahoj,

> Try downgrading numpy (I'm using 1.23.5, with conda
> as in `conda install numpy=1.23.5`),

no, I won't, that would mess up my distribution's packaging.

And I don't use AUTO, I just reported because I used to maintain the
Arch Linux AUR package for "auto-07p".

> or changing line 159 of
> ParseS.py from ``` if fdata == [] or len(fdata) != total: ``` to 
> ```
>             if fdata.tolist() == [] or len(fdata) != total:
> ```

Dito, I won't; I think the maintainers of AUTO should adapt to up to
date version of numpy.

Regards!

**Comment by znicolaou** [comment]
@dreirund AUTO is over 40 years old--the developers are largely approaching a well-deserved retirement. I think it is a DIY endeavor at this point...
